server:
  servlet:
    context-path: /api/v1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false&serverTimezone=UTC
    username: root
    password: root

logging:
  file:
    name: application.log